My first notebook!

In [5]:
print("Hello world")

Hello world


Checking my set up as I'm writing it locally


In [13]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

print(torch.randn(3, 3))
print(torch.cuda.is_available())
print(torch.__version__)

tensor([[-0.1841, -0.4935, -0.9276],
        [ 0.3837,  0.9061,  0.4361],
        [ 0.2055,  0.1893,  1.6509]])
True
2.7.0+cu126


Tensors are created with torch.tensor()

In [14]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [27]:
scalar.ndim
scalar.shape


torch.Size([])

In [22]:
vector = torch.tensor([7, 7])
vector
vector.ndim

vector.shape


torch.Size([2])

In [21]:
MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
MATRIX.ndim




2

In [30]:
TENSOR = torch.tensor([[[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]]])
TENSOR.ndim


4

In [31]:
TENSOR.shape 

torch.Size([1, 1, 3, 3])

In [37]:
random_tensor = torch.randn(3,2,4)
random_tensor


# torch.randn(number of matrices,number of rows,number of columns)
#so in our case, 3 matrices of 2x4 matrix

tensor([[[-1.1801, -1.2664,  0.3004, -0.8158],
         [ 0.3439,  0.6687, -1.0190,  0.9881]],

        [[ 0.8030,  0.9760,  1.1284, -1.3494],
         [-0.9681, -0.8765, -1.0912, -1.0990]],

        [[-0.2112, -2.0402, -1.7618, -0.2776],
         [ 0.9991,  1.5366,  1.4521,  0.8976]]])

In [33]:
random_image_tensor = torch.randn(256, 256,3)
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([256, 256, 3]))

### Zeros and Ones


In [38]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
ones = torch.ones(3,4)
ones



tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
zeros.dtype

torch.float32