My first notebook!

In [1]:
print("Hello world")

Hello world


Checking my set up as I'm writing it locally


In [2]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

print(torch.randn(3, 3))
print(torch.cuda.is_available())
print(torch.__version__)

tensor([[-1.8741, -1.0328, -0.2829],
        [ 0.3519,  0.0872,  2.0378],
        [ 0.9965,  0.0891,  0.0774]])
True
2.7.0+cu126


Tensors are created with torch.tensor()

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim
scalar.shape


torch.Size([])

In [5]:
vector = torch.tensor([7, 7])
vector
vector.ndim

vector.shape


torch.Size([2])

In [6]:
MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
MATRIX.ndim




2

In [7]:
TENSOR = torch.tensor([[[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]]])
TENSOR.ndim


4

In [8]:
TENSOR.shape 

torch.Size([1, 1, 3, 3])

In [9]:
random_tensor = torch.randn(2,3,2,4)
random_tensor


# torch.randn(number of matrices,number of rows,number of columns)
#so in our case, 3 matrices of 2x4 matrix

tensor([[[[-1.0090,  0.5981, -2.3943, -1.3513],
          [-0.5379, -0.3053,  0.2541, -1.0733]],

         [[ 0.0281,  1.1073,  1.0104,  0.9340],
          [-2.0048, -1.2015, -3.1494, -1.3143]],

         [[ 0.8375,  0.3922, -0.5094, -0.1222],
          [-0.8819, -0.3510, -1.1217,  0.1986]]],


        [[[ 0.4674, -0.1341, -0.0616, -0.4518],
          [ 0.4081, -0.5609,  0.4012, -0.3031]],

         [[ 0.0156, -0.4500, -0.0399,  0.0977],
          [ 0.0280, -1.0075, -0.0423,  0.5426]],

         [[ 0.0835, -1.1538, -1.4316,  1.2921],
          [-0.2201,  0.2688, -0.3307, -0.4572]]]])

In [10]:
random_image_tensor = torch.randn(256, 256,3)
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([256, 256, 3]))

### Zeros and Ones


In [11]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
ones = torch.ones(3,4)
ones



tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
zeros.dtype

torch.float32

torch arange

In [14]:
one_to_ten = torch.arange(1, 11)
peak = torch.arange(1, 100, 4)
one_to_ten, peak

#arange(start, end, step) where end is not included 


(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69,
         73, 77, 81, 85, 89, 93, 97]))

In [15]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=torch.float32,
                              device=None,
                              requires_grad=False)
float32_tensor

int16_tensor = torch.tensor([4,2,7],dtype=torch.int16,device = torch.device("cuda"))
int16_tensor






tensor([4, 2, 7], device='cuda:0', dtype=torch.int16)

3 common errors in pytorch:

1) Tensors not on the right device.
2) Tensors not thr right shape.
2) Tensors not the right datatype.



In [17]:
float32_tensor*int16_tensor


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
float32_tensor.device

In [18]:
tens = torch.rand(6,4)

tens






tensor([[0.6582, 0.8347, 0.5953, 0.9168],
        [0.0189, 0.6857, 0.6314, 0.1659],
        [0.4517, 0.9721, 0.1022, 0.8187],
        [0.8944, 0.9938, 0.6596, 0.6433],
        [0.0121, 0.4150, 0.3598, 0.2109],
        [0.5479, 0.5285, 0.7914, 0.7783]])

In [19]:
#Basic tensror attributes
print(tens)
print(f"Tensors shape: {tens.shape}")
print(f"Tensors datatype: {tens.dtype}")
print(f"Tensors device: {tens.device}")





tensor([[0.6582, 0.8347, 0.5953, 0.9168],
        [0.0189, 0.6857, 0.6314, 0.1659],
        [0.4517, 0.9721, 0.1022, 0.8187],
        [0.8944, 0.9938, 0.6596, 0.6433],
        [0.0121, 0.4150, 0.3598, 0.2109],
        [0.5479, 0.5285, 0.7914, 0.7783]])
Tensors shape: torch.Size([6, 4])
Tensors datatype: torch.float32
Tensors device: cpu
