### Tensor Manipulation!


In [85]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics


tensor = torch.tensor([1,2,3])
tensor + 10, tensor - 10


(tensor([11, 12, 13]), tensor([-9, -8, -7]))

In [86]:
tensor*10

tensor([10, 20, 30])

In [87]:
#built in function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [88]:
# Two waays of performing multiplication in matrices:
# Element Wise(scalar multiplication) and Dot product (matrix*matrix)
print(tensor,"*",tensor)
print(f"Equal: {tensor*tensor}")



tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [89]:
torch.matmul(tensor,tensor)

tensor(14)

In [90]:
 #here's where we get the most common error(mismatch of the shape)

torch.matmul(torch.rand(2,3),torch.rand(2,3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [91]:
#dimension of the matrices should be suck that number of coluumsn of the first and thre rows of the secnd should match

torch.matmul(torch.rand(2,3),torch.rand(3,2))
# we didnt get an error!, the reusilting matrix will have dimension of the outer dim

tensor([[0.6275, 0.3887],
        [1.1926, 0.8174]])

In [92]:
# we can fix our dimensions of the our matrix by transposing
# row becomes column and coulmun becomes row
tensor_A = torch.tensor([[1,2,4],[3,45,5]])
print(tensor_A.shape, tensor_A.T.shape) 
tensor_A, tensor_A.T

torch.Size([2, 3]) torch.Size([3, 2])


(tensor([[ 1,  2,  4],
         [ 3, 45,  5]]),
 tensor([[ 1,  3],
         [ 2, 45],
         [ 4,  5]]))

 ### Tensor Aggregation

In [93]:
x = torch.arange(0,100,10)
print(x)
x.min(),x.max()

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


(tensor(0), tensor(90))

In [94]:
x.mean()
# see how we get an error, datatype error!

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [95]:
# correct way to run iit would be, note torch,mean() needs float to work

torch.mean(x.type(torch.float16)), x.type(torch.float32).mean()

(tensor(45., dtype=torch.float16), tensor(45.))

In [96]:
x.sum()

tensor(450)

### Reshaping, stacking, squeezing and unsqueezing tensors

In [97]:
# reshaping - reshapes a tesnor to a defined shape
# stacking - combine mutiple tensors on top or side by side
# squeeze - removes all "1" dimensions from a tesnor
# unsqueeze - adds "1" dimension to a tensor 
# permute

p = torch.arange(1,11)
p,p.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [98]:

p_diff = p.reshape(5,2)
p_diff

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [99]:
z = p.view(1,10)
z,z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [100]:
# the vien function shares the same memory as the orginal tensor

z[:, 0] = 5
z,p

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [101]:
p_stacked = torch.stack([p,p,p], dim = 1)
p_stacked

tensor([[ 5,  5,  5],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]])

In [103]:
p_diff

tensor([[ 5,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [105]:
p.squeeze()

tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
p.unsqueeze(dim = 0)

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

 ### Indexing  
      

In [114]:
c = torch.arange(1,10).reshape(1,3,3)

c,c.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [115]:
print(c[0])
print(c[0][0])
print(c[0][0][0])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
