### Tensor Manipulation!


In [1]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics


tensor = torch.tensor([1,2,3])
tensor + 10, tensor - 10


(tensor([11, 12, 13]), tensor([-9, -8, -7]))

In [2]:
tensor*10

tensor([10, 20, 30])

In [3]:
#built in function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [4]:
# Two waays of performing multiplication in matrices:
# Element Wise(scalar multiplication) and Dot product (matrix*matrix)
print(tensor,"*",tensor)
print(f"Equal: {tensor*tensor}")



tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [5]:
torch.matmul(tensor,tensor)

tensor(14)

In [6]:
 #here's where we get the most common error(mismatch of the shape)

torch.matmul(torch.rand(2,3),torch.rand(2,3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [7]:
#dimension of the matrices should be suck that number of coluumsn of the first and thre rows of the secnd should match

torch.matmul(torch.rand(2,3),torch.rand(3,2))
# we didnt get an error!, the reusilting matrix will have dimension of the outer dim

tensor([[0.2591, 1.0445],
        [0.2917, 1.0323]])

In [8]:
# we can fix our dimensions of the our matrix by transposing
# row becomes column and coulmun becomes row
tensor_A = torch.tensor([[1,2,4],[3,45,5]])
print(tensor_A.shape, tensor_A.T.shape) 
tensor_A, tensor_A.T

torch.Size([2, 3]) torch.Size([3, 2])


(tensor([[ 1,  2,  4],
         [ 3, 45,  5]]),
 tensor([[ 1,  3],
         [ 2, 45],
         [ 4,  5]]))

 ### Tensor Aggregation

In [9]:
x = torch.arange(0,100,10)
print(x)
x.min(),x.max()

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


(tensor(0), tensor(90))

In [10]:
x.mean()
# see how we get an error, datatype error!

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [10]:
# correct way to run iit would be, note torch,mean() needs float to work

torch.mean(x.type(torch.float16)), x.type(torch.float32).mean()

(tensor(45., dtype=torch.float16), tensor(45.))

In [96]:
x.sum()

tensor(450)

### Reshaping, stacking, squeezing and unsqueezing tensors

In [13]:
# reshaping - reshapes a tesnor to a defined shape
# stacking - combine mutiple tensors on top or side by side
# squeeze - removes all "1" dimensions from a tesnor
# unsqueeze - adds "1" dimension to a tensor 
# permute

p = torch.arange(1,11)
p,p.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [14]:

p_diff = p.reshape(5,2)
p_diff

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [16]:
z = p.view(1,10)
z,z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [100]:
# the vien function shares the same memory as the orginal tensor

z[:, 0] = 5
z,p

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [17]:
p_stacked = torch.stack([p,p,p], dim = 1)
p_stacked

tensor([[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]])

In [18]:
p_diff

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [19]:
p.squeeze()

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
p.unsqueeze(dim = 0)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

 ### Indexing  
      

In [21]:
c = torch.arange(1,10).reshape(1,3,3)

c,c.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [23]:
print(c[0])
print(c[0][0])
print(c[0][0][0])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [22]:

m = torch.rand(1,2,3)
m

tensor([[[0.1413, 0.1361, 0.3875],
         [0.3598, 0.1007, 0.1160]]])

In [24]:
m[0],m[0][1],m[0][0][2]

(tensor([[0.1413, 0.1361, 0.3875],
         [0.3598, 0.1007, 0.1160]]),
 tensor([0.3598, 0.1007, 0.1160]),
 tensor(0.3875))

In [14]:
array = np.arange(1.0,8.0)

tensr = torch.from_numpy(array)
array,tensr


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [16]:
array = array + 1
array, tensr
#numpy creates a seperate tensor (from numpy)

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [18]:
#tensor to numpy
tensr = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1, 2, 3]), array([1, 2, 3]))

### Reproducability

working of a nueral network

` start with random nnumbers -> tensor operation -> update random numbers to try and make them better representation of the data -> again -> again `

We can reduce it by a concept of a **random seed**!
"flavour" of randomness!

In [20]:
random_tensor_A = torch.rand(3,4)   
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B) 

tensor([[0.1730, 0.4010, 0.5766, 0.3978],
        [0.7446, 0.1830, 0.5332, 0.6280],
        [0.3227, 0.8517, 0.6787, 0.9066]])
tensor([[0.7233, 0.3421, 0.0700, 0.7265],
        [0.4027, 0.2743, 0.5844, 0.0013],
        [0.3671, 0.8602, 0.2754, 0.3590]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [22]:
# lets make some random but reporducable tensors!
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_D==random_tensor_C)

# keep note that call of the manual_seed udually works only for 1 tesnsr

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### running on gpus

In [24]:
!nvidia-smi

Fri Jun 13 21:06:56 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.153.02             Driver Version: 570.153.02     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   42C    P3              8W /   30W |      12MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [25]:
torch.cuda.is_available()

True

In [26]:
# setup device agnostic code!
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [27]:
torch.cuda.device_count()

1

In [28]:

lol = torch.tensor([1,2,3])
print(lol,lol.device)


tensor([1, 2, 3]) cpu


In [29]:
lol_gpu = lol.to(device)
lol_gpu

tensor([1, 2, 3], device='cuda:0')

### note: NUMPY DOESNT WORK WITH A GPU!

In [31]:
lol_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [33]:
lol_back_to_cpu = lol_gpu.cpu().numpy()
lol_back_to_cpu

array([1, 2, 3])

In [34]:
lol_gpu

tensor([1, 2, 3], device='cuda:0')